name: ionic-mpnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit=2022.09          # 必须用 conda
  - pip                    # 启用 pip
  - pip:
    - tensorflow==2.12.0   # pip 版本支持 GPU
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - requests
    - tqdm
